# Jekyll settings
exclude:
  - "**/local"

include:
  - _pages

# Theme
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
title: "ALVaBeT 2024"
# subtitle: "The first workshop on Analysis of VAriation for BEtter Tools"
title_separator: "-"
emojicon: 🐍
locale: "en"
name: "L. Grobol"
timezone: Europe/Paris

# Hosting
url: "https://loicgrobol.github.io/"
baseurl: "/llcd/"
repository: "loicgrobol/llcd"
repo_branch: "main"

logo: # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"

og_image: # Open Graph/Twitter default site image

# Conversion
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
  sass_dir: _sass
  # style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap

atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: "nicer-wide"
      author_profile: false